(lang dune 3.11)

(name day1)

(generate_opam_files true)

(source
 (github An-Tu/advent_ocaml_2023))

(authors "An-Tu")

(maintainers "An-Tu")

(package
 (name day1)
 (depends ocaml dune iter))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
